### PR TITLE
Correct access tokens url

### PR DESCRIPTION
**Pull request by joshk**

### CODE REVIEW

**Comment by joshk** [comment]
@kerrizor @BanzaiMan is it possible to get this reviewed and deployed with the relevant apps that use this? I got an email from GitHub about it.

**Comment by anarosas** [comment]
Hi @joshk! 
What's the issue they emailed you about? I would like to have a bit more context, please

**Comment by joshk** [comment]
Hi @anarosas 

The link the in PR description gives some good detail about this change.

**Review by BanzaiMan — APPROVED** [review]

**Comment by anarosas** [comment]
I was looking everywhere for the link, it was hidden under the commit. Thank you Josh! 

For future reference: https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/

**Comment by BanzaiMan** [comment]
Hmm. I tried this on com-staging gatekeeper and this is what I get (https://papertrailapp.com/systems/travis-pro-gatekeeper-staging/events?q=program%3Aapp%2Fgator.1&focus=1012042418184396822) 

```
Dec 19 13:42:17 travis-pro-gatekeeper-staging app/gator.1: E TID=3880 Failed to obtain token from GitHub: 401 - {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}. job: {"queue":"build_requests","class":"Travis::Gatekeeper::Worker","args":[{"type":"api","credentials":{"token":null},"payload":"{\"repository\":{\"id\":151408743,\"owner_name\":\"BanzaiMan\",\"name\":\"com_testing\"},\"user\":{\"id\":33},\"id\":65301,\"message\":null,\"branch\":\"php\",\"config\":{}}"}],"retry":true,"jid":"f0177c60ec8b99e9e957fa14","created_at":1545226893.3057425,"enqueued_at":1545226937.3890064,"dead":false,"error_message":"Failed to obtain token from GitHub: 401 - {\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}","error_class":"RuntimeError","failed_at":1545226893.3915198,"retry_count":0} 
```

**Comment by BanzaiMan** [comment]
Is there anything else we are supposed to do?

**Comment by BanzaiMan** [comment]
Ah. I see it. It is `app`, not `apps`.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-github_apps/pull/15#issuecomment-448718443 The fix has been merged in all apps in production.

**Comment by anarosas** [comment]
thank you!!

**Pull request merged**
